In [ ]:
# pip install numpy
import numpy as np

In [ ]:
print(type([1,2,3]))
print(type(1,2,3))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))


In [4]:
np.zeros([5])

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((1))

array([0.])

In [14]:
np.zeros([5,7])


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [15]:
np.zeros([5,7,8])

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.,

In [18]:
np.zeros((5,6,8,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         ...,
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         ...,
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         ...,
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         ...,
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         ...,
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0

In [11]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
np.arange(4,20)  #  [4, 20[

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
np.arange(-5)  # solo con rangos los negativos

array([], dtype=int32)

In [23]:
np.arange(-2,1)

array([-2, -1,  0])

In [28]:
arreglo_pares = np.arange(0,20, 2) #el tercer parametro representa de cuanto en cuanto quiero moverme

In [25]:
np.arange(0.5,10, 2)

array([0.5, 2.5, 4.5, 6.5, 8.5])

In [26]:
np.arange(-12,1, 0.5)

array([-12. , -11.5, -11. , -10.5, -10. ,  -9.5,  -9. ,  -8.5,  -8. ,
        -7.5,  -7. ,  -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5,
        -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ,   0.5])

In [32]:
print(arreglo_pares.size)
print(len(arreglo_pares))
arreglo_tres_dimensiones = np.zeros((2,3,4))
print(arreglo_tres_dimensiones.shape)

10
10
(2, 3, 4)


In [39]:
arreglo_pares.shape
arreglo_pares.reshape(5,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [40]:
arreglo_pares.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [42]:
arreglo_24 = np.arange(0,24)

In [44]:
arreglo_24.reshape(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [45]:
arreglo_24.reshape(2,12)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [46]:
arreglo_24.reshape(12,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [47]:
arreglo_24.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [48]:
arreglo_24.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [49]:
arreglo_24.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [50]:
arreglo_24.reshape(6,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [51]:
arreglo_24.reshape(1,24)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [53]:
arreglo_24.reshape(2,2,6)


array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [54]:
a = np.array([10,10,10])
b = np.array([5,5,5])


In [59]:
print(a + b)  #suma


[15 15 15]
[5 5 5]
[15 15 15]
[15 15 15]


In [58]:
np.arange(24).reshape(2,12).reshape(2,2,6)

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [60]:
print(a - b) #resta

[5 5 5]


In [61]:
print(a * b)  # multiplicacion

[50 50 50]


In [62]:
print(a / b)  #division

[2. 2. 2.]


In [101]:
arreglo_tridimensional = np.arange((5,6,8))

TypeError: arange: scalar arguments expected instead of a tuple.

In [94]:
arreglo2_tridimensional = np.arange((5,6,8))

array([5])

In [93]:
arreglo2_tridimensional + arreglo_tridimensional

array([10])

array([5])

In [87]:
a % b #mod

array([0, 0, 0], dtype=int32)

In [88]:
arreglo_tridimensional % arreglo2_tridimensional

array([0], dtype=int32)

In [89]:
arreglo_tres_dimensiones

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [108]:
#multiplicar
print(a * 10)

#sumar
print(a + 10)

#restar
print(a - 10)

#dividir
print(a / 10)

# = igualar   NO SE PUEDE
#  print(a = 3)

#mod
print(a % 3)

[100 100 100]
[20 20 20]
[0 0 0]
[1. 1. 1.]
[1 1 1]


In [110]:
arreglo_muestra = np.arange(20).reshape(5,2,2)   # arreglo de 20 elementos y tridimensional
arreglo_muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [116]:
resp = arreglo_muestra > 5


In [115]:
print(resp)

[[[False False]
  [False False]]

 [[False False]
  [ True  True]]

 [[ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]]]


In [136]:
arreglo_muestra[resp]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [187]:
# sacar de 6 a 14 y divisibles para 2
arreglo_muestra[(arreglo_muestra>5) * (arreglo_muestra<12) * (arreglo_muestra%2==0)]

array([ 6,  8, 10])

In [192]:
# sacar de 6 a 14 otra opcion
resp_mayor5 = arreglo_muestra > 5
arreglo_muestra[resp_mayor5]
resp_menor12 = arreglo_muestra < 12
arreglo_muestra[resp_menor12]
arreglo_muestra[resp_mayor5 & resp_menor12]



array([ 6,  7,  8,  9, 10, 11])

In [193]:
resp = (arreglo_muestra > 5) & (arreglo_muestra < 12) & (arreglo_muestra % 2 == 0)  
arreglo_muestra[resp]

array([ 6,  8, 10])

In [194]:
A = np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [196]:
B = np.arange(4,8).reshape((2,2))
B

array([[4, 5],
       [6, 7]])

In [197]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [198]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [199]:
B.dot(A)

array([[10, 19],
       [14, 27]])

In [200]:
np.dot(B,A)

array([[10, 19],
       [14, 27]])

In [201]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [203]:
#suma de todo el arreglo
arreglo_doce.sum()


66

In [205]:
# minimo y maximo del arreglo
arreglo_doce.min()


<function ndarray.min>

In [ ]:
arreglo_doce.max