In [2]:
import numpy as np


In [2]:
arreglo_0_a_90_grados = np.array([0,30,45,60,90])
arreglo_0_a_90_grados

array([ 0, 30, 45, 60, 90])

In [3]:
radianes = arreglo_0_a_90_grados * np.pi / 180
radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [4]:
np.sin(radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [5]:
np.cos(radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [6]:
np.tan(radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [5]:
arreglo_random = np.random.randint(
    11   #enteros positivos hasta
)
arreglo_random

6

In [8]:
arreglo_random = np.random.randint(
    -1,
    2           #enteros positivos desde [-1 hasta [1
)
arreglo_random

1

In [18]:
arreglo_random = np.random.randint(
    0, #minimo
    11, #maximo
    3  #randoms
)
arreglo_random

array([9, 7, 8])

In [19]:
np.median(arreglo_random)   #sacar mediana


8.0

In [20]:
np.std(arreglo_random)   #desviacion estandar

0.816496580927726

In [21]:
np.var(arreglo_random)  #varianza


0.6666666666666666