## 1) Examen Lopez Juan

# 2) Crear un vector de ceros de tamaño 10

In [3]:
import numpy as np
vector_zeros = np.zeros(10)
print(vector_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# 3) Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1

In [4]:
vector_zeros_un_uno = np.zeros(10)
vector_zeros_un_uno[4]=1
print(vector_zeros_un_uno)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 4) Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc.

In [7]:
elementos_cincuenta = np.arange(50)
invertido = elementos_cincuenta[::-1]
print(invertido)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


# 5) Crear una matriz de 3 x 3 con valores del cero al 8

In [13]:
matriz_tres = np.arange(9).reshape(3,3)
print(matriz_tres)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 6) Encontrar los indices que no sean cero en un arreglo

In [17]:
import numpy as np
arreglo = [1,2,0,0,4,0]

no_zeros = np.nonzero(arreglo)
print(f'Los indices son:{no_zeros}')

Los indices son:(array([0, 1, 4], dtype=int64),)


# 7) Crear una matriz de identidad 3 x 3

In [20]:
identidad = np.eye(3)
print(identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 8) Crear una matriz 3 x 3 x 3 con valores randomicos

In [22]:
matriz_tresd = np.random.random((3,3,3))
print(matriz_tresd)

[[[0.72468432 0.38739685 0.86588571]
  [0.93484814 0.20062665 0.82194434]
  [0.94287837 0.6690916  0.30504025]]

 [[0.7041081  0.18259676 0.23118795]
  [0.78911816 0.79085669 0.72631121]
  [0.00744179 0.12142294 0.60531509]]

 [[0.15538989 0.65006054 0.8279027 ]
  [0.90342926 0.39763751 0.2394241 ]
  [0.96258391 0.51602444 0.14584774]]]


# 9) Crear una matriz 10 x 10 y encontrar el mayor y el menor

In [27]:
matriz_diez = np.random.random((10,10))
print(matriz_diez)
print(f'\nEl mayor valor de la matriz es: {matriz_diez.max()}')
print(f'\nEl mayor valor de la matriz es: {matriz_diez.min()}')

[[0.9898885  0.93971085 0.19325072 0.70147056 0.82079287 0.12159167
  0.25198352 0.54118504 0.52945521 0.6877645 ]
 [0.08744036 0.78332734 0.45370472 0.0573308  0.16023923 0.13451453
  0.19632332 0.93561922 0.3765107  0.16292084]
 [0.01436356 0.75865177 0.18233371 0.34804112 0.31625643 0.12613119
  0.25513683 0.58022807 0.21610356 0.39394438]
 [0.94401884 0.65493512 0.79897937 0.86567031 0.20568183 0.8656668
  0.79143301 0.92685893 0.19948191 0.27061318]
 [0.66118508 0.06366111 0.77417384 0.09875434 0.775833   0.85053102
  0.42834344 0.19722686 0.88169986 0.65536084]
 [0.8064666  0.83206053 0.95693101 0.90889675 0.09411259 0.82387414
  0.00428885 0.29540983 0.93599987 0.54939028]
 [0.99935248 0.02209157 0.0485324  0.06544926 0.77659717 0.07444484
  0.7189547  0.16771532 0.89903986 0.64379062]
 [0.0129873  0.00133644 0.22661053 0.88510959 0.13272227 0.94586028
  0.67943479 0.39385145 0.53916149 0.84661674]
 [0.60421254 0.01061184 0.4085112  0.95820772 0.01493852 0.23217629
  0.25981255 

# 10) Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)

In [144]:
from scipy import ndimage
from scipy import misc

img = misc.face()
rgb = np.unique(img.reshape(-1, img.shape[2]), axis=0)
print(rgb)
print('--> 3 colores')


[[  0   0   5]
 [  0   0   7]
 [  0   0   9]
 ...
 [255 248 255]
 [255 249 255]
 [255 252 255]]
--> 3 colores


# 11) ¿Como crear una serie de una lista, diccionario o arreglo?

In [107]:
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

import pandas as pd
serie_lista = pd.Series(mylist)
serie_array = pd.Series(myarr)
serie_dict = pd.Series(mydict)
#print(serie_dict)

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


# 12) ¿Como convertir el indice de una serie en una columna de un DataFrame?

In [41]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 
# Transformar la serie en dataframe y hacer una columna indice

#print(ser)
dt = ser.to_frame().reset_index
print(dt)

<bound method DataFrame.reset_index of     0
a   0
b   1
c   2
e   3
d   4
f   5
g   6
h   7
i   8
j   9
k  10
l  11
m  12
n  13
o  14
p  15
q  16
r  17
s  18
t  19
u  20
v  21
w  22
x  23
y  24
z  25>


# 13) ¿Como combinar varias series para hacer un DataFrame?

In [109]:
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

df_de_series = pd.DataFrame({'Serie 1': ser1 , 'Serie 2' : ser2})
print(df_de_series)

   Serie 1  Serie 2
0        a        0
1        b        1
2        c        2
3        e        3
4        d        4
5        f        5
6        g        6
7        h        7
8        i        8
9        j        9
10       k       10
11       l       11
12       m       12
13       n       13
14       o       14
15       p       15
16       q       16
17       r       17
18       s       18
19       t       19
20       u       20
21       v       21
22       w       22
23       x       23
24       y       24
25       z       25


# 14) ¿Como obtener los items que esten en una serie A y no en una serie B?

In [114]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
a_no_en_b = ser1[~ser1.isin(ser2)]

print(f'Los items de A que no estan en B son:\n{a_no_en_b}')

Los items de A que no estan en B son:
0    1
1    2
2    3
dtype: int64


# 15) ¿Como obtener los items que no son comunes en una serie A y serie B?

In [116]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

a_no_en_b = ser1[~ser1.isin(ser2)]
b_no_en_a = ser2[~ser2.isin(ser1)]
no_comunes_a_b = np.append(a_no_en_b, b_no_en_a)
print(f'Los items que no son comunes en A y B son: {no_comunes_a_b} ')

Los items que no son comunes en A y B son: [1 2 3 6 7 8] 


# 16) ¿Como obtener el numero de veces que se repite un valor en una serie?

In [121]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
print('valor/repeticiones')
print(ser.value_counts())

valor/repeticiones
d    7
g    5
h    4
a    3
b    3
e    3
f    3
c    2
dtype: int64


# 17) ¿Como mantener los 2 valores mas repetidos de una serie, y a los demas valores cambiarles por 0 ?

In [124]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
print('Serie')
print(ser)
print('\nValor/Repeticiones')
print(ser.value_counts())
ser[~ser.isin(ser.value_counts().index[:2])] = 0
print('\nSerie con ceros')
print(ser)

Serie
0     2
1     1
2     1
3     4
4     3
5     4
6     4
7     4
8     4
9     2
10    3
11    1
dtype: int32

Valor/Repeticiones
4    5
1    3
3    2
2    2
dtype: int64

Serie con ceros
0     0
1     1
2     1
3     4
4     0
5     4
6     4
7     4
8     4
9     0
10    0
11    1
dtype: int32


# 18) ¿Como transformar una serie de un arreglo de numpy a un DataFrame con un shape definido?

In [87]:
#ser = pd.Series(np.random.randint(1, 10, 35))
#shape(7,5)

df_arreglo = pd.DataFrame(ser.values.reshape(7,5))
print(df_arreglo)

   0  1  2  3  4
0  4  4  1  2  5
1  8  7  8  4  3
2  9  6  9  5  2
3  7  4  4  5  9
4  1  2  2  2  5
5  9  5  1  2  9
6  8  8  2  8  1


# 19) ¿Obtener los valores de una serie conociendo la posicion por indice?

In [88]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
# a e i o u

ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

# 20) ¿Como anadir series vertical u horizontalmente a un DataFrame?

In [92]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

#ser1.append(ser2)
df = pd.concat([ser1, ser2], axis=1)
print(df)

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


# 21)¿Obtener la media de una serie agrupada por otra serie?
### groupby tambien esta disponible en series.

In [128]:
frutas = pd.Series(np.random.choice(['manzana', 'banana', 'zanahoria'], 10))
pesos = pd.Series(np.linspace(1, 10, 10))
#print(pesos.tolist())
#print(frutas.tolist())
#> [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
#> ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']

# Los valores van a cambiar por ser random
# apple     6.0
# banana    4.0
# carrot    5.8
# dtype: float64


pesos.groupby(frutas).mean()

banana       6.5
manzana      3.0
zanahoria    6.0
dtype: float64

# 22)¿Como importar solo columnas especificas de un archivo csv?

In [136]:
#https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv.
path_archivo = 'https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv'

df_completo = pd.read_csv(path_archivo)
#print(df_completo)

columnas = ['crim', 'dis','rad', 'ptratio']
df_columnas = pd.read_csv(path_archivo,  usecols=columnas)
print(df_columnas.head())

      crim     dis  rad  ptratio
0  0.00632  4.0900    1     15.3
1  0.02731  4.9671    2     17.8
2  0.02729  4.9671    2     17.8
3  0.03237  6.0622    3     18.7
4  0.06905  6.0622    3     18.7
